source $HOME '~/.config/nvim/general/settings.vim'
source $HOME '~/.config/nvim/plugins/vim-plugins.vim'
source $HOME '~/.config/nvim/plugins/vim-plugins-config.vim'
source $HOME '~/.config/nvim/themes/appearance.vim'
source $HOME '~/.config/nvim/mapping/keymaps.vim'
